FROM node:14 as builder

# WORKDIR in docker container
WORKDIR /stockwatch/frontend

# Docker uses caching so install all the dependencies first
COPY package.json .
RUN npm install

# Source code changes much more often so easier to rebuild the image when you structure like this
# copy react app to the container
COPY . .

RUN npm run build

# prepare nginx
FROM nginx
COPY --from=builder /stockwatch/frontend/build /usr/share/nginx/html