version: "3.8"
services:
    # backend:
    #     depends_on:
    #         - mongodb
    #     build: ./backend
    #     environment:
    #         - DB_NAME=$DB_NAME
    #         - PORT=$API_PORT
    #         - PGHOST=db
    #         - PGPORT=$DB_PORT
    #         - PGUSER=$DB_USER
    #         - PGPASSWORD=$DB_PASSWORD
    #         - PGDATABASE=$DB_NAME
    #     ports:
    #         - $API_PORT:$API_PORT
    #     volumes:
    #         - ./backend:/app
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.prod
        ports:
            - "8080:80"
        # env_file:
        #     - ./.env
    # mongodb:
    #     image: mongo
    #     container_name: mongodb
    #     environment:
    #         MONGO_INITDB_ROOT_USERNAME: myadmin
    #         MONGO_INITDB_ROOT_PASSWORD: mypassword
    #     ports:
    #         - $DB_PORT:$DB_PORT
    #     volumes:
    #         - mongodb_data:/data/db
# volumes:
#     mongodb_data:
