version: "3.8"
services:
    frontend:
        build:
            context: ./frontend
        volumes:
            - /frontend/node_modules
            - ./frontend/src:/frontend/src
        env_file:
            - ./.env
        environment:
            - WDS_SOCKET_PORT=0 # Fixes bug where websocket connection is fixed to default port 3000
    backend:
        build:
            context: ./backend
        volumes:
            - ./backend:/backend
        env_file:
            - ./.env
        environment:
            MONGO_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:${MONGO_PORT}/${MONGO_DB_NAME}?authSource=admin #or mongodb://mongo:27017/stockwatch
            POSTGRES_URI: postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
        depends_on:
            - mongo
            - postgres
        stdin_open: true # For pdb
        tty: true # For pdb i think
    nginx:
        restart: always
        depends_on:
            - frontend
            - backend
        build:
            context: ./nginx
        ports:
            - 8080:80
    mongo:
        image: mongo
        restart: always
        ports:
            - ${MONGO_PORT}:${MONGO_PORT}
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
        volumes:
            - mongodb-data:/data/db
    postgres:
        image: postgres
        restart: always
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        environment:
            POSTGRES_USER: ${POSTGRES_USERNAME}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
volumes:
    mongodb-data:
        name: stockwatch-mongo-data
        # driver: local # default driver is local
    postgres-data:
        name: postgres-data
        # driver: local # default driver is local
