version: "3.8"
services:
    frontend:
        build:
            context: ./frontend
        ports:
            - "3000:3000"
        volumes:
            - ./frontend/src:/stockwatch/frontend/src
        env_file:
            - ./.env
